[25] DUMBHAX: setAudioPortCallback(); is refactored in Marshmallow
This single function is now handled by two functions:

* addAudioPortCallback();
* removeAudioPortCallback();

Plus a couple of new functions. see:

* frameworks/av/media/libmedia/AudioSystem.cpp
* frameworks/av/include/media/AudioSystem.h

* frameworks/base/core/jni/android_media_AudioSystem.cpp

/home/adfad666/B2GCM2/gecko/dom/system/gonk/AudioManager.cpp:768: error: undefined reference to 'android::AudioSystem::setAudioPortCallback(android::sp<android::AudioSystem::AudioPortCallback>)'
/home/adfad666/B2GCM2/gecko/dom/system/gonk/AudioManager.cpp:707: error: undefined reference to 'android::AudioSystem::setAudioPortCallback(android::sp<android::AudioSystem::AudioPortCallback>)'

Signed-off-by: Adam Farden <adam@farden.cz>