[24] HAX: Work around wrong header include
Gecko has a MediaResource.h header but now Android Marshmallow
has a header with the same name. Some Gecko files are picking
up the Android header instead of the Gecko header, causing
build failure.

Symlink to a different name and include the symlink instead.

../../../../gecko/dom/media/omx/MediaStreamSource.h:23:20: error: 'MediaResourceIndex' in namespace 'mozilla' does not name a type
  typedef mozilla::MediaResourceIndex MediaResourceIndex;

Signed-off-by: Adam Farden <adam@farden.cz>